### PR TITLE
Fix BOOST_LIBRARIES not set problem and poolminer link error(miss OpenSSL) 

### PR DESCRIPTION
**Pull request by hackfisher**
For unknown reason(upgrade to cmake 2.8.12?),  ${Boost_LIBRARIES} are now case sensitive and so BOOST_LIBRARIES was not set during find_package.

OpenSSL libraries are missed due to parent CMakeList.txt change?

Here is the pull request to fix, can reproduce by delete cache of Cmake on Window before merge this pull request.

should be common issue, but this was found ant tested on windows.

### CODE REVIEW

**Comment by vogel76** [comment]
Hi, I am working on a fix related to Cmakelist.txt too - nowadays they came to be total mess and will be cleared soon. Especially boost/openssl detection will be moved to the single place (fc) and then propagated to outer modules.
I disagree to change KH_STATC_QT to 0 by default since it will break our release scheme & build process. But I will change the cmake code to set it to 1 only if such variable was not yet defined so you will be able then to pass -DKH_STATC_QT=0 switch to the cmake spawn. I hope it is acceptable solution for both sides :-)

**Comment by hackfisher** [comment]
hi vogel76,

I agree and I only changed KH_STATC_QT to 0 in my fork branch, when I provide this pull request, I've pay attention to change it back to 1.

Please pay attention to the case sensitive problems of "BOOST_LIBRARIES" which this pull request try to fix.

**Comment by hackfisher** [comment]
I'm not sure.

In subdirectory Bitshares, there already exsits
set( BOOST_LIBRARIES ${Boost_THREAD_LIBRARY} ${Boost_SYSTEM_LIBRARY} ${Boost_FILESYSTEM_LIBRARY} ${Boost_DATE_TIME_LIBRARY} ${Boost_CHRONO_LIBRARY} ${ALL_OPENSSL_LIBRARIES} ${Boost_COROUTINE_LIBRARY} ${Boost_CONTEXT_LIBRARY} ${pthread} PARENT_SCOPE )

we may use PARENT_SCOPE to make it visual to parent, but this one-by-one item-list setting is with less flexibility.

**Comment by vogel76** [comment]
yes I know about these problems. Such variable (BOOST_LIBRARIES) really never should be written at client code - it should be set by FindBoost.cmake module. As I said it was to big mess and I'm near to clean it up (I am while checking linux platform right now, windows build succeeded)

**Comment by vogel76** [comment]
I have committed changes related to cmakelists.txt rewrite. Application builds fine right now on windows and linux too

**Pull request closed without merging**
